<a href="https://colab.research.google.com/github/Ammar-Asim-23/Ammar-Asim-23/blob/main/ML_Lab1_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Exercise: NumPy Basics

* Create a NumPy array with values ranging from 0 to 9.
* Reshape the array into a 3x3 matrix.
* Perform element-wise addition, subtraction, multiplication, and division with a scalar value of 2.
* Calculate the mean, median, and standard deviation of the array.
* Create a new array with values ranging from 10 to 18.
* Perform element-wise multiplication between the two arrays.
* Transpose the second array.
* Compute the dot product between the first and the transposed second array.

In [4]:
import numpy as np

arr1 = np.arange(9)

arr1 = arr1.reshape(3, 3)

addition_result = arr1 + 2
subtraction_result = arr1 - 2
multiplication_result = arr1 * 2
division_result = arr1 / 2

mean_value = np.mean(arr1)
median_value = np.median(arr1)
std_deviation_value = np.std(arr1)

arr2 = np.arange(10, 19).reshape(3,3)

elementwise_multiplication = arr1 * arr2

arr2_transposed = arr2.reshape(3, 3).T

dot_product_result = np.dot(arr1, arr2_transposed)

print("Original Array:")
print(arr1)
print("\nAddition with Scalar (2):")
print(addition_result)
print("\nSubtraction with Scalar (2):")
print(subtraction_result)
print("\nMultiplication with Scalar (2):")
print(multiplication_result)
print("\nDivision with Scalar (2):")
print(division_result)
print("\nMean of the Array:", mean_value)
print("Median of the Array:", median_value)
print("Standard Deviation of the Array:", std_deviation_value)
print("\nSecond Array:")
print(arr2)
print("\nElement-wise Multiplication between the Two Arrays:")
print(elementwise_multiplication)
print("\nTransposed Second Array:")
print(arr2_transposed)
print("\nDot Product between the First and the Transposed Second Array:")
print(dot_product_result)


Original Array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Addition with Scalar (2):
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

Subtraction with Scalar (2):
[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]

Multiplication with Scalar (2):
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]

Division with Scalar (2):
[[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]

Mean of the Array: 4.0
Median of the Array: 4.0
Standard Deviation of the Array: 2.581988897471611

Second Array:
[[10 11 12]
 [13 14 15]
 [16 17 18]]

Element-wise Multiplication between the Two Arrays:
[[  0  11  24]
 [ 39  56  75]
 [ 96 119 144]]

Transposed Second Array:
[[10 13 16]
 [11 14 17]
 [12 15 18]]

Dot Product between the First and the Transposed Second Array:
[[ 35  44  53]
 [134 170 206]
 [233 296 359]]


# Exercise: Slicing NumPy Arrays

* Create a NumPy array with values ranging from 0 to 19.
* Extract the elements from index 5 to index 10.
* Extract every other element from the array.
* Create a 2D NumPy array of shape (4, 4) with consecutive integers starting from 0.
* Extract the second column of the 2D array.
* Extract the elements from the third row.
* Extract a 2x2 sub-matrix from the top-left corner of the 2D array.
* Extract a 2x2 sub-matrix from the bottom-right corner of the 2D array.
* Reverse the order of elements in the entire array.
Reverse the order of elements in each row of the 2D array.

In [5]:
import numpy as np

arr = np.arange(20)

extracted_range = arr[5:11]

every_other_element = arr[::2]

arr_2d = np.arange(16).reshape(4, 4)

second_column = arr_2d[:, 1]

third_row = arr_2d[2, :]

top_left_submatrix = arr_2d[:2, :2]

bottom_right_submatrix = arr_2d[2:, 2:]

reversed_array = np.flip(arr)

reversed_rows_array = np.flip(arr_2d, axis=1)

print("Original Array:")
print(arr)
print("\nExtracted Range (Index 5 to Index 10):")
print(extracted_range)
print("\nEvery Other Element:")
print(every_other_element)
print("\n2D Array:")
print(arr_2d)
print("\nSecond Column:")
print(second_column)
print("\nThird Row:")
print(third_row)
print("\nTop Left Sub-matrix (2x2):")
print(top_left_submatrix)
print("\nBottom Right Sub-matrix (2x2):")
print(bottom_right_submatrix)
print("\nReversed Array:")
print(reversed_array)
print("\nReversed Rows in the 2D Array:")
print(reversed_rows_array)


Original Array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Extracted Range (Index 5 to Index 10):
[ 5  6  7  8  9 10]

Every Other Element:
[ 0  2  4  6  8 10 12 14 16 18]

2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Second Column:
[ 1  5  9 13]

Third Row:
[ 8  9 10 11]

Top Left Sub-matrix (2x2):
[[0 1]
 [4 5]]

Bottom Right Sub-matrix (2x2):
[[10 11]
 [14 15]]

Reversed Array:
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]

Reversed Rows in the 2D Array:
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]
